# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TabWriter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TabWriter
  pod 'Firebase/MLModelInterpreter'
  pod 'TensorFlowLiteSwift'
  pod 'Firebase/Analytics'
  pod 'Charts'
  pod 'TinyConstraints'

end

# You can setup your podfile to automatically match the deployment target of all the podfiles to your # current project deployment target like this :
post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
end