model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(32, kernel_size = (3, 3), activation=tf.nn.relu, input_shape=(192, 9, 1)))
model.add(tf.keras.layers.Conv2D(64, kernel_size = (3, 3), activation=tf.nn.relu))
model.add(tf.keras.layers.Conv2D(64, kernel_size = (3, 3), activation=tf.nn.relu))
model.add(tf.keras.layers.MaxPooling2D(pool_size = (2,2)))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(6*19))
model.add(tf.keras.layers.Reshape((6, 19)))
model.add(tf.keras.layers.Activation(activation=tf.nn.softmax))
model.summary()